language: node_js
node_js:
- '7'
env:
  global:
    - EXTENSION_ID=mieiidjehfdcknlieknkmadkkchcepgj
    - CLIENT_ID=822187143060-qs1ujs0doanvuc3bvvuf4jjviqlne133.apps.googleusercontent.com
    - secure: H7AQx/MB8WFPuxVrM016VcakhnV2cYVAVskp3zuug/gKygpz3gM+vGYMu+/EMZKaBqq31LRGLjyuebMi99C8ZZUQQrXG3jD8P3LpXtVbBfwDZh2WLzHy6gMDBlE0xGRs2kk10y1obUR/ZyjzW7TmqK2Hj6EsqqgLc6bM75fRolF5Csfr35IZHGabMZr3iaPYgS1G4HMTELnly1c5srt/AOcz4yNZ5lnA211hcH3ZMfVZAC/56Cu7CS+j9atLqklXBA27e0Vweuk0ZCb58uMeJpzZSbDjK3i8hS3ENtwsKHNqTOOxidx7e3wB5yl7Mgl1OMjtdP0/hdc0M1JBuSQyNlgPFvHSUUeAd6zLLgIEaPeSLEynkQnX+3xNUwjnFVTqLAj+0jdo4wHlXaACL6ngeB7+5iHdBalnxTgrXdNM+wlWRBi0vbLrTBShATgJfr4W5jqTyNQ4f9FJlypBSC9oeCA5K0NU210kRBHBp2wPujHoDZJzbjzce110svJrGA/QeK8CXGcYnsNPi+0jRWOt46nE/Kym8/uATG96ZqnSOuOydCCclr7tEaZLXpMfTqR9e3oiwiajuQcT4wMpLoeo8OQgvtw6pYDysIqk+GqyZghBivPTBKYbe7euCILDT0S21ok9NtyYmJ7HKwtvh5SPURlrPAJqRqVcFBe9cLzpNl0=
    - secure: epJbTMUrHObkN9S/7cQAYwMl7OJG05U0cL3JoE4lRP+mIolujAFbSfWlh++KDciSAWKW7CRLNFYn7k0795cfSlgsjy7FDEDkiCMPJ8fDVqBMwSfysGge3Sn7jh6USgJts8NN7gdtJUtcGae6pAF9BgJzJaZsd7Myhg24BnG9yPc+HO2ZQwdMs0cPAdd62dc+++XHmfFj9iD1ffJVQTRQOGFUzfJZm7O8R501UptQWp4nrR1knWO+Y39Du+VESW0UBd86N6o540YDf9mTBWlcbGLkkBu/qFRf6coL5YDXnpkQmJevLWW6kqM1pOKjEH9K0Ml5rzyOr3rDMbt2uT5gr4J0IycqEC+MYS+M5z1TqR6rmUW7Ax/0m8VfKostR5Nll6z5GWKBmcKvgDw6RV5sEv9pvOmnEfL9ua8DJGGAN0hmOwEHni2JVB3X5Y5bdmjIulp+az9xtAQIAWzvbnn2ZEhuaasvQ12gDPDQ4l3Kcy138VhEi8OHSpSAkpTuVPKaZhxKdgpU8+PS4SwLdVJJN4dtJJD4PeijZZ0MLuSy5r1fgBSwDyc/NElOmr9VcIlDc9WtS/T/ldbqzkuHNG9Km9I5JQniJJ6h/3DnBcU7FtyEiKceFTJ/4auOmfONkQ7kjoIuTq8i/fJLrXu/axqkiWNj6uQciW7hlf82yo250Ic=
before_install:
- npm install -g chrome-webstore-upload-cli@^1.0.0
# Only build tags
if: tag IS present
deploy:
  provider: script
  script: npm run release
  on:
    branch: master
    tags: true
